#!/usr/bin/env python
import sys
import string

# Convert a list of options into an html select element

if len(sys.argv) < 2:
    print "Usage: ./options filename"
    exit(1)

file = open(sys.argv[1])

i = 0
for line in file:
    i = i + 1
    """    # First make the country name usable for the value
    lowercase = string.lower(line)
    # Now replace spaces with -
    dashed = string.replace(lowercase, ' ', '-') 
    # And get rid of leading and trailing whitespace
    stripped = string.strip(dashed)"""
    line = string.strip(line)
    # Never mind, just use numbers, and make an array later
    print '<option value="' + str(i) + '">' + line + '</option>',
